name: Workflow-CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-and-model:
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: file://${{ github.workspace }}/MLProject/mlruns
      MLFLOW_EXPERIMENT_NAME: mushroom-logreg-classifier

    steps:
    - name: Run actions/checkout@v3
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.7

    - name: Check Env
      run: |
        echo "Python version:"
        python --version
        echo "Current directory:"
        pwd
        echo "Files:"
        ls -la
    - name: Install dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        environment-file: MLProject/conda.yaml
        activate-environment: mlflow-env
        python-version: 3.12.7
        auto-activate-base: false

    - name: Run mlflow project
      run: |
        conda run -n mlflow-env mlflow run MLProject --env-manager=conda

    - name: Get latest MLflow run_id
      id: get-run-id
      run: |
        echo "Isi dari MLProject/mlruns/0:"
        ls -la MLProject/mlruns/0 || echo "Direktori belum ada atau kosong"
    
        latest_run=$(find MLProject/mlruns/0 -mindepth 1 -maxdepth 1 -type d | sort -r | head -n 1)
        
        if [ -z "$latest_run" ]; then
          echo "Tidak ditemukan direktori run ID!"
          exit 1
        fi
    
        run_id=$(basename "$latest_run")
        echo "run_id=$run_id"
        echo "run_id=$run_id" >> $GITHUB_OUTPUT

    - name: Install Python dependencies (again, inside shell)
      run: |
        pip install mlflow

    - name: Upload artifact ke GitHub repository
      uses: actions/upload-artifact@v4
      with:
        name: trained-model-artifacts
        path: MLProject/mlruns/

    - name: Build Docker Model
      run: |
        MODEL_URI=MLProject/mlruns/0/${{ steps.get-run-id.outputs.run_id }}/artifacts/model
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/mushroom-logreg:latest
        mlflow models build-docker --model-uri $MODEL_URI --name $IMAGE_NAME
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Docker Image
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/mushroom-logreg:latest \
                   ${{ secrets.DOCKER_USERNAME }}/mushroom-logreg:${{ github.run_number }}
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/mushroom-logreg:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/mushroom-logreg:${{ github.run_number }}
